// Declarations for modules without types
declare module 'next-themes'
declare module '@next/bundle-analyzer'
declare module 'github-slugger'
declare module 'inquirer'
declare module 'dedent'
declare module 'prettier'
declare module 'express'
declare module 'tailwindcss/defaultTheme'
declare module 'tailwindcss/colors'
declare module '@tailwindcss/forms'
declare module '@tailwindcss/typography'
