import Head from "next/head";
import Layout from "./Layout";
import Banner from "./Banner";
import About from "./About";
import Skills from "./Skills";
import Portfolio from "./Portfolio";
import Resume from "./Resume";
import Contact from "./Contact";

export default function PortfolioLanding() {
  return (
    <Layout>
      <Head>
        <title>Mojib Mohammad | Personal Portfolio | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blog/authors/mojib.png" />
      </Head>
      <Banner />
      <About />
      <Skills />
      <Portfolio />
      <Resume />
      <Contact />
    </Layout>
  );
}
