import Head from "next/head";
import About from "../components/About";
import Layout from "../components/Layout";
import Portfolio from "../components/Portfolio";
import Resume from "../components/Resume";
import Banner from "../components/Banner";
import Skills from "../components/Skills";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Mojib&apos;s Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <About />
      <Skills />
      <Portfolio />
      <Resume />
      <Contact />
    </Layout>
  );
}
